import type { Metadata } from "next";
import "./globals.css";
import GlobalStateManager from "@/Utils/GlobalStateManager";
import Toast from "@/Utils/Toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GlobalStateManager>{children}</GlobalStateManager>
      </body>
    </html>
  );
}
