import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sadhana",
  description: "Generated by sanjivanipune.com",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className="w-full h-full">
        {children}
      </div>
  );
}
